### ISSUE TITLE
--merge-directories causes files to be deleted in tagged folder even with --keep-tagged

### ISSUE THREAD

**Issue by phiresky** [sahib/rmlint#141]
Minimal example:
```bash
mkdir -p origs/folder/subfolder
echo test > origs/folder/subfolder/file
cp -r origs/folder origs/samefolder
cp -r origs dups
rmlint -D -k -m dups // origs
```

Output:

```
# Duplicate Directorie(s):
    ls -la /tmp/22.01.29/origs
    rm -rf /tmp/22.01.29/dups
    ls -la /tmp/22.01.29/origs/folder
    rm -rf /tmp/22.01.29/origs/samefolder

==> In total 4 files, whereof 2 are duplicates in 1 groups.
==> This equals 10 B of duplicates which could be removed.

Wrote a sh file to: /tmp/22.01.29/rmlint.sh
Wrote a json file to: /tmp/22.01.29/rmlint.json
```

It deletes `/origs/samefolder` which it shouldn't.

Otherwise, great feature!

```
rmlint --version
version 2.2.0 compiled: May 10 2015 at [12:04:50] "Dreary Dropbear" (rev 187f1c2)
```

**Comment by SeeSpotRun** [comment]
Thanks for picking this up.
@sahib maybe time for a simpler treemerge algorithm taking advantage of the pathricia trie?

eg maybe reference count each folder path in the trie during traversal (including reference count for subdirs, unfollowed symlinks, dirs below maxdepth etc).  Then when each file is tagged for deletion, unref the path.  If a folder path refcount gets to 0 then unref its parent.

Of course to map the originals of the files to be deleted, you would need to include a list of "originals" to the trie node, but that shouldn't be difficult.

As for "clustering up" the originals ... I think that is always at risk of throwing exceptions so maybe better off without it...

**Comment by sahib** [comment]
Hi @phiresky, 

I will look into fixing it later or tomorrow. I think that actually worked earlier...

@SeeSpotRun: I actually think the treemerge code is quite okay in it's current state. The current approach is inspired by https://en.wikipedia.org/wiki/Merkle_tree, without having it as explicit data structure in order to handle many special cases. I agree it could be simpler at times with the unified trie, but in the current case it's mostly nicely separated from the rest of the code. I would really like to prevent having more stuff pulled into other modules (especially shredder).

How would your approach tackle recursive duplicates (i.e. the original directory contains duplicates or duplicate directories itself) like in the example by @phiresky?

**Comment by sahib** [comment]
This should be mostly fixed in ``develop``. 
Found another issue on the way though, ``-K`` does not appear to work correctly here either.

**Comment by sahib** [comment]
Okay, that last issue should be resolved too after some late-night action.
@phiresky, can you validate it works like expected?

**Comment by phiresky** [comment]
Thanks! I can confirm as of e22da7e9ca0598b57b0b5cd210adce4f90c3a954 it is fixed for the ~25GB data set I found this problem with.

**Comment by SeeSpotRun** [comment]
@sahib - happy with your solution.  I had tried to come up with a buxfix for treemerge but got stuck trying to get the -K case to work, so was just brainstorming up alternative approaches.
