### ISSUE TITLE
Can't start GUI

### ISSUE THREAD

**Issue by guillefar** [sahib/rmlint#159]
I compiled the last version in Linux Mint 17.2, and the Shredder menu option was created, but does nothing. 

If I run in the console ` rmlint --gui `, I get this error: 
`/usr/bin/python3: No module named shredder`

**Comment by sahib** [comment]
Hello. 

This error usually indicates that shredder was not installed (I assume it was though, due to the menu entry) or that python can't find it since it's not in python's ``sys.path``. This is probably the same issue as #153.

As noted in #153, this is mostly a problem of Ubuntu (I guess Linux Mint is affected too).

In short:

- ``setup.py`` scripts (the install mechanism of python packages) 
  install their files to ``/usr/lib/pythonX.Y/site-packages/``. 
  I guess this could be changed, but the documentation does not tell me how, neither it might be a good idea for other distributions.
- Ubuntu expects the packages to be at ``/usr/lib/pythonX.Y/dist-packages``. No idea why.
  This seems to break a lot of packages for no good reason.
- You can check which pathes are checked for python packges with:

     ``python3 -c 'import sys; print(sys.path)'``. 

   On my system that is:

     ``['', '/usr/lib/python35.zip', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-linux', '/usr/lib/python3.5/lib-dynload', '/usr/lib/python3.5/site-packages']``

So the solution would be to add the ``site-packages`` path to your python-paths.
You can try the following (replace X.Y with your python version from ``python --version``):

- ``export PYTHONPATH="$PYTHONPATH:/usr/lib/pythonX.Y/site-packages"; rmlint --gui``
- Ask a Ubuntu dev what Im supposed to do here.

**Comment by guillefar** [comment]
Hi, thanks, that fixed apparently, but then I got this: 

```
Could not import colorlog
Traceback (most recent call last):        

  File "<frozen importlib._bootstrap>", line 2158, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):       

  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)       

  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code  
    exec(code, run_globals)      

  File "/usr/lib/python3.4/site-packages/shredder/__main__.py", line 23, in <module>
    from shredder.application import Application     

  File "/usr/lib/python3.4/site-packages/shredder/application.py", line 17, in <module>
    from gi.repository import Gtk, Gio, Rsvg, GdkPixbuf
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 53, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name Rsvg, introspection typelib not found 
```

**Comment by sahib** [comment]
That probably means that you don't have ``rsvg`` installed. 
This might be the right package:

  http://packages.ubuntu.com/vivid/gir1.2-rsvg-2.0

A packager would make the installation process a lot more straight forward...

**Comment by guillefar** [comment]
Perhaps you want to add  gir1.2-rsvg to the list of packages to install for ubuntu. 
This happened, though: 

![shreder](https://cloud.githubusercontent.com/assets/1972792/10719057/efd4e89c-7b80-11e5-8c82-21071fbbc170.png)

It just show just a gray square. 

The console output was: 

````
Could not import colorlog
01:26:28 INFO     [__main__.py: 29] root: Starting up.
01:26:28 INFO     [application.py:102] application: Loading resources from: /usr/lib/python3.4/site-packages/shredder/resources/shredder.gresource
01:26:28 DEBUG    [application.py:144] application: Instancing views.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/shredder/application.py", line 145, in do_startup
    self.win.views.add_view(SettingsView(self), 'settings')
  File "/usr/lib/python3.4/site-packages/shredder/views/settings.py", line 164, in __init__
    self.build()
  File "/usr/lib/python3.4/site-packages/shredder/views/settings.py", line 292, in build
    self.append_entry(*entry[1:])
  File "/usr/lib/python3.4/site-packages/shredder/views/settings.py", line 224, in append_entry
    sep_row.set_activatable(False)
AttributeError: 'ListBoxRow' object has no attribute 'set_activatable'

```

**Comment by sahib** [comment]
Hi,

that one is my fault - at least partially. You most likely have a too old Gtk version (``< 3.14``, you can check with e.g. ``pkg-config --modversion gtk+-3.0``).

I only tested the GUI on systems with 3.14 or more recent, since I expected older versions to disappear before we release it. Seems I was wrong.

I pushed a fix to ``master``, just do a ``git pull`` and try again. It might however yield other exceptions.
Will also add the gui dependencies to the install instructions later.

**Comment by guillefar** [comment]
Output of pkg-config --modversion gtk+-3.0

```
Package gtk+-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-3.0' found
```
I think I have installed it, If I'm not mistaken Cinnamon uses gtk3 libraries. 

In any case, I pulled and compiled it again, but no luck, same thing happens. 

Also, I received this message while compiling it, not sure if has anything to do with it: 

`Cannot import sphinx_bootstrap_theme; falling back to 'nature'.`

**Comment by sahib** [comment]
No worries, that just means you don't have the gtk3 devel files installed.
From a quick google search, you gtk version is probably 3.10 - which is already two years old.

The GUI needs some widgets that are only present in 3.12 and up (and some minor stuff that I think cam in 3.14). So, the only fix I can offer you currently, is that you need to upgrade your gtk version (and therefore probably your distribution).

That other message you found is harmless. It simply means that the html documentation will be rendered less pretty locally.
