### ISSUE TITLE
Feature Request: 'Undo'

### ISSUE THREAD

**Issue by marc1uk** [sahib/rmlint#162]
Despite a few years of using linux I still find myself making a mess of tricky installations (geant4 for example), and undoubtedly have a huge amount of half-baked and redundant installation files lying around stuffing up my filesystem. rmlint seems like a great tool to try to clear out the crap, but when dealing with bunked installations, I'm not always clear what needs to be kept and what's safe to delete. 
So my feature request is this: the documentation (which is great, btw) already mentions that you can modify the rmlint.sh to move files to a temporary location instead of deleting them. What would be great would be a little extension to this that stored the original file locations, and created another script that could move them back if things went tits up.

**Comment by SeeSpotRun** [comment]
I think the best way would be via an existing utility such as [gvfs-trash](http://manned.org/gvfs-trash/d5c95fac) or [trash-cli](https://github.com/andreafrancia/trash-cli).

We could make the shell script check for existence of either utility and if yes, call it instead of `rm -rf`.  Would probably need to add a `-r` option to the shell script if the user wants to force the use of `rm`.

Not to hijack your issue, but I'm wondering whether having a `-c` (confirm) option when calling the shell script would be useful, to prompt for user confirmation before deleting each file (Y)es/(**N**)o/(A)ll/(C)ancel?  Actually this could be the default behaviour, since we already have the `-d` option to "do not ask".

**Comment by sahib** [comment]
You can basically actually do this already: 

```bash
# rmlint.sh now moves dupes to trash via trash-cli
# Later you can restore any file with ``trash-restore <file>``. 
rmlint -c sh:cmd='trash-put "$2"'
```

*Note to self:* Found a formatting bug with files with quotes in them when using ``-c sh:cmd``.

> We could make the shell script check for existence of either utility and if yes, call it instead
> of rm -rf. Would probably need to add a -r option to the shell script if the user 
> wants to force the use of rm.

I don't think we should check for those tools, rather let the user specify the tool that's trendy today.

> Not to hijack your issue, but I'm wondering whether having a -c (confirm) option when calling the
>  shell script would be useful, to prompt for user confirmation before deleting each file 
> (Y)es/(N)o/(A)ll/(C)ancel? Actually this could be the default behaviour, since we already
> have the -d option to "do not ask".

Not a big fan to be honest, Im already annoyed enough when software asks me that and I keep typing ``Y`` till I find the ``A`` option, while being confused what ``A`` will do when I selected ``N`` before.
I simple believe that ``rmlint`` should be as non-interactive/interrupting as possible, ``-d`` is just there to remind people that they will trigger a dangerous operation.

**Comment by SeeSpotRun** [comment]
@sahib re quotes - that's not the same as #148?
@marc1uk - while I agree with sahib (I'd forgotten how easy it was to change the remove command when running rmlint), https://github.com/SeeSpotRun/rmlint/tree/feature/trash is a quick rendition of `-t` as a `rmlint-sh` run-time option to use trash instead of rm.

**Comment by sahib** [comment]
@SeeSpotRun: Sorry, you're right. Should have been ``$1``. I think deleting empty files/dirs is still okay, since we generally consider them as other sort of lint. ``-T df`` would at least spare those files if no deletion is desired. Also, :+1: for adding it to the guide. 

(P.S: I think that bug was just me being not a morning person...)

**Comment by SeeSpotRun** [comment]
Just to annoy @sahib: https://github.com/SeeSpotRun/rmlint/tree/feature/interactive-sh

**Comment by marc1uk** [comment]
Wow thats a lot of responses! Thanks a lot guys, I kinda expected this to be straightforward, but you've made it look embarassingly so! :+1: At least I'll be much more confident now than if I'd tentatively been fiddling with my own dodgy scripts. 

P.S. small note; in your 'Gentle Guide' you specify options -e and -i, but the examples below both use -e; i think the second should read
# Find all duplicate files that have the same extension:
$ rmlint -i some_dir/
