### ISSUE TITLE
Unicode/UTF-8 filename issue

### ISSUE THREAD

**Issue by bjornfor** [sahib/rmlint#191]
I have some file paths with multi-byte characters encoded as UTF-8. The generated rmlint.sh (and rmlint.json) file then contain wrong paths:

```
[...]
remove_cmd '/mnt/data/pictures/2006/mottatte_bilder_pÃ¥_telefon/image1.jpg [...]
```

The above should have been:

```
[...]
remove_cmd '/mnt/data/pictures/2006/mottatte_bilder_på_telefon/image1.jpg [...]
```

That single 'å' character has been wrongly converted to two characters 'Ã¥'. I guess rmlint treats file paths as ASCII?

I'm running Linux with rmlint 2.4.4 (latest).

**Comment by sahib** [comment]
Hey there.

It should actually work, since ``rmlint`` treats paths like a byte sequence.
At least, this simple testcase worked for me ([and we even have another test for that](https://github.com/sahib/rmlint/blob/master/tests/test_options/test_replay.py#L205)):

```bash
$ mkdir -p /tmp/mottatte_bilder_på_telefon
$ echo xxx > /tmp/mottatte_bilder_på_telefon/a.png
$ echo xxx > /tmp/mottatte_bilder_på_telefon/b.png
$ rmlint /tmp/mottatte_bilder_på_telefon
```

Both ``rmlint.sh`` and the terminal output show the *å*. Is just ``rmlint.sh`` wrong or also the terminal output? What about the ``json`` output (``rmlint -o json``)? 

Also, please paste the output of:

```bash
$ echo $LANG
```

**Comment by bjornfor** [comment]
Huh, that's weird. I can successfully run your above test... the 'å' is preserved in the terminal output and in rmlint.sh/rmlint.json. But I'm still able to reproduce my initial problem when run abainst _that particular data set_. Btw, when it's broken, it's only in rmlint.sh/rmlint.json. The terminal output is correct.

Do you know anything I can do to try narrowing down why the test case works but not when run on my real data?

```
$ echo $LANG
en_US.UTF-8
```

**Comment by bjornfor** [comment]
Very interesting find:

```
$ rmlint .   # broken utf8 in rmlint.sh/.json
```

```
$ rmlint ./2006/  # all fine
```

From what I can tell, the directory depth makes a difference. I tried reproducing this by extending that above test case, but I didn't manage (utf8 is fine). But the "directory" depth difference is definitely reproducible on my real data. I'll dig some more.

**Comment by sahib** [comment]
I can only guess.

It might be worth noting that the filesystem encoding might not be necessarily ``utf-8`` (or any other unicode based encoding), since [a filesystem does not usually care about encoding](https://unix.stackexchange.com/questions/2089/what-charset-encoding-is-used-for-filenames-and-paths-on-linux). In your case it might as well be ``latin-1``. Especially data from older usb sticks with documents from windows might vary in what path encoding was used. 

Can't really say why it's displayed fine in the terminal though :smile:, I'll look at the code later.

**Comment by bjornfor** [comment]
Nope, my bad. This is PEBKAC! I thought I viewed rmlint.sh as utf8, based on Vim's ":set enc?" returning "encoding=utf-8". But I should have used ":set fileencoding?", because that returns "encoding=latin1"!! So the rmlint.sh and rmlint.json files have been correct all along....

Sorry!

What's funny though is that Vim's interpretation of the encoding (latin1 vs utf-8) changed between me doing different rmlint runs (varying directory depth causing different data to be output etc.). It fooled me into thinking that _rmlint_ changed. But it was just Vim...

**Comment by bjornfor** [comment]
When forcing vim to read the file as utf8 (":e ++enc=utf8") I found the real issue with my data set. I had some old files with illegal byte sequences in them (stuff from Win95 -- you were spot on!)... So Vim thought it was better to use latin1 than utf8 when showing me the file :-)

**Comment by sahib** [comment]
No problem, glad you found that. I guess ``rmlint.sh`` runs through fine?

The behaviour of vim might even be sensible: Vim does 'guessing' on the character encoding. The longer
the path is, the more confident it gets in it's decision. Some characters like å are hard to tell apart, since they have the [same codepoint](http://www.amp-what.com/unicode/search/%C3%A5) in both ``latin-1`` and ``utf-8``  (see also [wikipedia](https://en.wikipedia.org/wiki/Latin-1_Supplement_(Unicode_block))).

**Comment by bjornfor** [comment]
> I guess rmlint.sh runs through fine?

I have only dry-run it so far on this data set. I need to carefully review rmlint.sh before letting it churn though all my pictures :-)

But the paths look fine in my editor now that I know to ensure the correct encoding. So I don't expect any issues. And I'll fixup those old Win95 (or WinXP more likely) files with invalid encoding that I have.
