### ISSUE TITLE
Speed up comparison of large files

### ISSUE THREAD

**Issue by claell** [sahib/rmlint#200]
I am using rmlint to find duplicate video files. Since they are pretty big it takes a long time to compare them. Thus I'd like to have an option to speed the comparison up a bit, maybe with only doing partial checksum generation.

**Comment by sahib** [comment]
This option already exists: ``--clamp-low`` / ``--clamp-top`` (or ``-q`` / ``-Q``).
They can be used to only read a certain part of a file. Example:

```bash
# Only read the middle of each file (+/- 10% of the respective file size)
$ rmlint -q 40% -Q 60% large-files/
```

Otherwise the comparison won't get much faster without loosing accuracy.

**Comment by claell** [comment]
Thanks for the fast reply. This is very useful.

**Comment by claell** [comment]
Just a question: Wouldn't it be better to check large files in chunks rather than just a segment to know better whether they are equal?

**Comment by sahib** [comment]
I'm not sure where you draw the difference between *chunks* and *segments* and what exactly *better* means in this context. I guess this will likely answer your question:

``rmlint`` is doing *incremental hashing*, i.e. it reads equal sized chunks of data from a group of equal sized files and hashes them (if not in paranoia mode). If one or more files differ, they build a new group in the next iteration. If a group still contains more than one file at the end it will be printed. It's actually [pretty fast](http://rmlint.readthedocs.io/en/latest/benchmarks.html) (if that's your *better*) since we [implemented some tricks to read files in order or read only a minimum amount from them](http://rmlint.readthedocs.io/en/latest/developers.html#optimizations).


You can read about the gory details here:
https://github.com/sahib/rmlint/blob/master/lib/shredder.c#L47

**Comment by claell** [comment]
What I meant is if a file is very large I maybe only want to hash 5% of it to save time. This can currently only done by defining a single segment. But I think it would be better to spread the 5% over the file in small chunks.

**Comment by sahib** [comment]
Ah, misunderstood you then. This would be very hard to implement with the current design of ``rmlint``.  Not because it's so bad, but because it sees a file as continous stream of bytes that has no holes in it. 

Also note that jumping through a large file has a cost itself: Seeking. This is especially slow on rotational disks. Most files should be filtered by looking at their middle part, I guess only a few extra files would be recognized when using your strategy.

**Comment by claell** [comment]
Alrigh. It is just that my video files with same size are identical almost every time so the hashing is not really needed. However I noted that some files where treated as duplicates with only 10% hashed and not when using complete hashing. But that might be caused by writing or download issues.
So then I probably continue to use the clamp method to speed comparison up.
