### ISSUE TITLE
Add colour code for files that will be kept/deleted in rmlint.sh

### ISSUE THREAD

**Issue by claell** [sahib/rmlint#201]
When reviewing which files are kept/deleted with `rmlint.sh -n` colours would make reading much easier.
For example use red for deleted files and green for kept ones.

**Comment by sahib** [comment]
Indeed, this might be useful. Will implement.

**Comment by sahib** [comment]
Done as of f96564b. I did go for yellow, since red is reserved for errors.

![alt](http://i.imgur.com/rLPZe5t.png)

Solved?

**Comment by claell** [comment]
Actually I was thinking about using colours for the filenames, since I had pretty long paths and it was difficult to find out which one is kept and which is deleted.

**Comment by sahib** [comment]
Considered that, but, out of experience, long colored text is quite hard to digest depending on the used colorscheme (and I saw lots of bad examples of that). Since I know that many people still use ``rmlint`` with a [pixelish font in xterm and the default color scheme](https://andrewharvey4.files.wordpress.com/2009/12/xterm-man.png), I would prefer not to overuse colors. Therefore the colored prefix that should be "enough" to visually distinguish orignals/duplicates and several groups of duplicates.

**Comment by claell** [comment]
Alright, agree that readability is decreased this way. It is just pretty hard to see what will be done with a certain file at a glimpse when the path is very long.

**Comment by sahib** [comment]
Okay. 

As noted in #202, you can go the extra mile and provide an extra script that does the colorization for you:

```bash
$ rmlint -c 'sh:cmd=echo -e "\e[0;31mDeleting: $1\e[0m"; rm -rf $1' /tmp
```

**Comment by claell** [comment]
Thanks, will use this and close this issue.
