### ISSUE TITLE
MacOS GUI Non-Operable, Directed to Incorrectly Named App

### ISSUE THREAD

**Issue by SainteCelery** [sahib/rmlint#221]
running:
 `rmlint --gui` 

results in:
`python3: posix_spawn: /usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/Resources/Python.app/Contents/MacOS/Python: Undefined error: 0`

The app in that path is named 'Python 3(.app)' not 'Python.app'.

**Comment by sahib** [comment]
And how did you install ``rmlint``?

**Comment by SainteCelery** [comment]
Homebrew

**Comment by sahib** [comment]
I'm sorry, but I have no clue about that. 
Someone with more experience with macOS should weight in here.
I'm not even sure here is the right place to report that, maybe you should open an issue for the homebrew formula.

**Comment by sahib** [comment]
I had some temporary access to an iMac and did not manage to reproduce that kind of error.
The gui did startup, and, albeit missing lots of icons, it seemed to work otherwise.

My best guess is that something in your python(3) configuration is wrong. ``rmlint`` is really only executing some script, but judging from your error it doesn't even get there. Can you execute ``python3 -c "import shredder"`` on the commandline?

If you don't have additional input I will close this in a few days.
