### ISSUE TITLE
shell script handling of duplicate dirs somewhat broken

### ISSUE THREAD

**Issue by SeeSpotRun** [sahib/rmlint#225]
I noticed a few issues with duplicate dir handling in rmlint.sh, which maybe opens up a broader philosophical discussion...

The reflink handler is broken; this results in deleting the contents of the duplicate directory:
```
$ rmlint <path> -D -c sh:handler=reflink
<snip>
$ ./rmlint.sh
<snip>
```
That one is easy to fix (just needs `--archive` in the shell script `cp --reflink=always` line).

The clone handler fails with `ERROR: btrfs clone: error 21: failed to open dest file.`  I don't think there is any good fix for this.  The shell script could try to recursively clone the files, but that might fail since treemerge is just matching dir contents and doesn't care about file names or even subdirs.

More generally, I think there is an incompatibility between duplicate dir detection and the various link handlers (symlink/hardlink/reflink/clone).  An example to highlight this:
```
$ mkdir -p testdir/dir1 testdir/dir2
$ rm -rf testdir
$ mkdir -p testdir/dir1 testdir/dir2
$ echo "same" > testdir/dir1/foo
$ echo "same" > testdir/dir2/bar
$ tree testdir
testdir
├── dir1
│   └── foo
└── dir2
    └── bar

$ rmlint -D -c sh:handler=hardlink testdir
<snip>
$ ./rmlint.sh
<snip>
$ tree testdir
testdir
├── dir1
│   └── foo
└── dir2
    └── foo
```

Also the `-p` option to reconfirm duplicates before deletion, doesn't work with identical dirs.

For me, treemerge is more informational (hey, these dir's are identical!) rather than transactional (`rm -rf` may look nicer than lots of individual `rm`'s, but both get the job done, and the former is arguably riskier).  I think there's a case to keep the treemerge output separate from the duplicate handling.

**Comment by sahib** [comment]
You raise some valid points there, although I do not agree fully on the conclusion,
since I consider those points as solvable. But yes, we can agree that the current state is broken.

> That one is easy to fix (just needs --archive in the shell script cp --reflink=always line).

Okay, I will look into that, since I changed something there recently anyways. 

> The clone handler fails with ERROR: btrfs clone: error 21: failed to open dest file. I don't think there is any good fix for this. The shell script could try to recursively clone the files, but that might fail since treemerge is just matching dir contents and doesn't care about file names or even subdirs.

That's true and can be considered as a bug. From my point of view the only correct solution is
removing the duplicate dir(s) and recursively reflinking all files from the original directory.
It's completely true that this may (likely) result in a different directory layout since treemerge
sees directories kind of as one big blob (which is consistent, since ``rmlint`` only compares about content, not path names etc.).

> More generally, I think there is an incompatibility between duplicate dir detection and the various link handlers (symlink/hardlink/reflink/clone). An example to highlight this:

Just because it took me a bit till I noticed what you mean and maybe someone else reads this:
*After the linking, ``dir2`` has the same name ``foo``, although it was named ``bar`` before.*

But this is the same case as above. ``rmlint`` created an exact copy of ``dir1`` regarding content.
We never did any promise about the layout of the content.

**Sidenote:** I changed something regarding that recently. When hardlinking and symlinking
duplicate dirs are deleted before calling the ``cp`` command, since ``cp`` did not hardlink
the file even with ``--remove-destination`` if the file already existed. This might be the cause
of your confusion, since (I think) it did work like you expected before.

> Also the -p option to reconfirm duplicates before deletion, doesn't work with identical dirs.

That's true, but I would consider paying the price by implementing something that can compare directories in a compatible way to ``rmlint`` (...probably by just using ``rmlint``). My only open question is to do that before the release or after (and to disable -p for duplicate dirs for now).

> For me, treemerge is more informational (hey, these dir's are identical!) rather than transactional (rm -rf may look nicer than lots of individual rm's, but both get the job done, and the former is arguably riskier). I think there's a case to keep the treemerge output separate from the duplicate handling.

I really don't like that, but you mentioned it goes more into a philosophical discussion at that point... :smirk:
It's true that treating directories as bag of single files get the job done, but my concern is the user interface. We tell users to look at the output of ``rmlint.sh`` (or ``.json``), so we should do everything
to make that easy (or possible at least). Displaying huge list of duplicate files instead one or two
duplicate dir lines feels counter-intuitive. Sure, we could insert some hints in the script, but that solves the issue only partially imho. I also recognize that you also consider the current state as broken, but I don't think changing it to a mere information would make any of these problems actually go away, but rather shift them on the users (matching files to duplicate directories).

Also note that displaying duplicate dirs in the rmlint output, but not in the gui would be inconsistent (because ``rmlint.json`` would not contain duplicate directories with your logic, so the GUI could not show them.)

**Comment by SeeSpotRun** [comment]
Good discussion thanks.

Regarding the above inconsistencies, I think there are two options:
1.  Just declare the sh:[hardlink|reflink|clone] handlers to be incompatible with treemerge.  Why?  Because these options all imply that the user wants to recover the disk space but preserve the duplicate paths.  In other words the duplicate path is important.  Clobbering the paths with a different tree (but same file contents) may not be what the user wanted.
2.  Change the treemerge algorithm to require identical tree structure, not just identical content.

Regarding the rmlint.sh `-p` option, I think we just document it as incompatible with treemerge and add a line in rmlint.sh.in to produce an appropriate error message whenever the handler is passed a dir when `-p` is set.

**Comment by sahib** [comment]
> Regarding the above inconsistencies, I think there are two options:

As already mentioned above, I would add option 3:

3. Document that treemerge will find directories with the same content, but not with the same layout.
    On the long run it might also possible to add a switch to optionally require treemerge to look for identical
    layout (this is actually a lot simpler, I think and it is the same as your option 2).  That way, the user can 
    decide if he wants to force the same layout if he wants. With this definition of treemerge (possible 
    overwrite layout if content equal), we should be able to have a well defined ``sh:{hardlink,reflink,clone}`` etc. By the way: ``sh:symlink`` couldn't even work any other way. ``clone`` will probably take the most work though...
    

> Just declare the sh:[hardlink|reflink|clone] handlers to be incompatible with treemerge. Why? Because these options all imply that the user wants to recover the disk space but preserve the duplicate paths. In other words the duplicate path is important. Clobbering the paths with a different tree (but same file contents) may not be what the user wanted.

It's kind of hard to judge what the users want or expects. And it may or may not be something that makes sense. It took me for example quite some time to figure out what's wrong with your example from above.
From my point of view it felt logical to me to have two *exact* same directories (layout + content) afterwards. Okay, Sure. I'm an exception here, since I wrote that felony called treemerge, but other users might feel the same. My point is that we can hardly figure out what the user wants, but need to try to be consistent with how ``rmlint`` works. And for me consistency means that duplicate directories are lint that have the same content, but not necessarily the same layout - since it's the same for duplicate files.

> Regarding the rmlint.sh -p option, I think we just document it as incompatible with treemerge and add a line in rmlint.sh.in to produce an appropriate error message whenever the handler is passed a dir when -p is set.

I would prefer to add a new (possibly generally useful) ``--equal`` option that compares two files (or directories) and checks if both are equal. If so, exit with status code 0, otherwise with status code 1.
This could be used instead of the current ``cmp`` command.

**Comment by sahib** [comment]
Okay, I had some fun with all of that.

Here's what I did:

- Fix a bug in ``treemerge`` that sometimes did not recognize dirs as dupes, even if they had the same content. Interestingly enough it was because the path layout somehow got mixed into the comparison. Also treemerge should be now a bit faster since it does not calculate the digest of all children anymore when merging up...
- Add some clarification about treemerge in the man page.
- I added a new ``--equal`` option that compares two (or more) files (or directories) with each other.
  If they are equal, an exist state of 0 is returned by ``rmlint``. This works similar to the ``cmp`` utility
  and is used in it's place by the shellscript to support comparing directories.
- I added a new ``--honour-dir-layout`` (short ``-j`` so I could write ``-DjT nonstripped``, you know why).
  This option makes treemerge also look at the tree layout for the comparison. This feature needs a bit more testing though.
- Add ``--archive`` to the commandline as per your suggestion.
- Spit our a warning for now when ``-c sh:clone`` or ``-c sh:handler=clone`` is used in combination with ``-D`` (without ``-j``) until I figured a better solution for this. I had a misunderstanding here from your text, since
this is the only part that actually requires the same layout of two duplicate directories. An easy fix would be deleting the duplicate directory, copying all original files and calling that clone functionality on that. Or fallback to reflink for duplicate directories. Anyways, what was the advantage of ``clone`` over ``reflink`` again?

Together with the previous changes (delete the duplicate directory before attempting to {hard,soft,ref}link)
this issue should be mostly solved. Or at least in a state that allows a release without bad feelings.

**Comment by sahib** [comment]
Tests are currently not running through, as far as I could tell, the problem was introduced by one of your commits: https://github.com/sahib/rmlint/commit/87858846bca59923e8abcf66479db3d5b5c42824 It segfaults now because  treemerge gets an ``file->digest == NULL`` when running for example this:

```
$ mkdir x
$ echo 1 > x/1
$ ln x/1 x/1_hardlink
# No duplicate directories, but results get piped through treemerge.c 
$ rmlint -D x/1 x/1_hardlink  anyways.
ERROR: Assertion failed [...]
```

Problem seems to be that for hardlink only groups that checksum vanishes too early.
*Sidenote:* bug report out of my memory; account for errors. :stuck_out_tongue:

**Comment by sahib** [comment]
I figured it out myself after reading my own comment. A group with only hardlinks won't have a digest of course. In this case treemerge needs to be more clever to also match based on dev/inode. A stupid quickfix
would be to calculate a checksum based on dev/inode, but that's too hacky.

**Comment by sahib** [comment]
Should be fixed now as part of those two commits:

e64fbe1 Save the path of the rmlint binary for rmlint.sh (for --equal and --btrfs-clone)
dc1ce8a Fix the hardlink handling in treemerge

Anything left on this issue, besides ``clone``?

**Comment by SeeSpotRun** [comment]
Sorry for not joining in sooner - have been away.

> dc1ce8a Fix the hardlink handling in treemerge

Doesn't seem to work for me:
```
$ #### Test normal case (works as expected):
$ mkdir dir_a dir_b
$ echo data > dir_a/file
$ echo data > dir_b/file
$ ./rmlint -D dir_a dir_b
# Duplicate Directorie(s):
    ls -la '/<pwd>/dir_a'
    rm -rf '/<pwd>/dir_b'
...
$ #### Test hardlinked case (fails to detect duplicate dirs):
$ mkdir dir_a dir_b
$ echo data > dir_a/file
$ ln dir_a/file dir_b/file
$ ./rmlint -D dir_a dir_b
# Duplicate(s):
    ls '/<pwd>/dir_a/file'
    rm '/<pwd>/dir_b/file'
...
```

> Related question: If we have a sub group in shredder that only consists of hardlinks, do we end up with
half-finished checksums in file->digest?

Yes I think so.  Depending where the file differences are detected, this could generate several different scenarios which would be difficult for treemerge to handle.  I think it's probably better to require fully hashed hardlinks when treemerge is in play.  I'll have a look at a patch for shredder to do that.

**Comment by sahib** [comment]
No worries, won't be here for the next two weeks myself.

You're right, my fix will not work well for partial hardlinks and might lead to false positives in the worst case.
Might also have different problems beside that. I will revert it. I guess we won't have a different option than what you're doing in your branch. :cry: 

Another problem (a solvable one though I think): We do not output the checksum in ``rmlint.json`` for hardlink only groups. And we would also output partial checksums for subgroups with only hardlinks...
This will probably break the GUI since it relies on having each file a checksum filled in (it uses it to group files iirc). I think we should not output partial checksums in any case and introduce a ``group_id`` (a running count that's unique for each group) in the ``rmlint.json`` output that points to a files of the same group and use that for the GUI.

**Comment by sahib** [comment]
I cherry-picked your patch to fully hash files when using treemerge. I also reverted my changes.
Is there anything left on this issue (providing unittests pass....)?

**Comment by SeeSpotRun** [comment]
I haven't tested it out (I don't tend to use treemerge anyway) but you seem to have covered all the issues.  Closing...
