### ISSUE TITLE
Adding a progress number in rmlint.sh

### ISSUE THREAD

**Issue by antoniocaruso** [sahib/rmlint#226]
Dear rmlint authors,

First of all, thanks for this fantastic tool, I use it regularly to keep clean up old photo library.
I'd like to suggest a simple improvement:

Deleting lots of file with rmlint.sh, expecially with the -p options requires a good amount of time, expecially if done on external slow disks.
I already know that we can customize the output, but I would suggest to add maybe in the -p case only a counter of the number of file deleted paired to the total number.
So we have something like:

[100/1000] keeping
[100/1000] deleting.
[101/1000] keeping..
etc.
or a percentage, or whatever indication of progress.
Thanks.

**Comment by sahib** [comment]
This is actually a nice idea and should be implemented.

One problem I see is that the shellscript is written while we're still scanning (in most cases it least...),
so we do not necessarily know the number of groups until the very end. We would need to do some postprocessing after the script was finished. Certainly do-able though.

**Comment by SeeSpotRun** [comment]
Working prototype in https://github.com/SeeSpotRun/rmlint/tree/feature/sh-progress-counter.

**Comment by sahib** [comment]
Sorry, apparently my previous comment somehow got lost...

I actually already did implement that  (f9ae3c7a8553fa3c9f14a0e7ca770540e35f3402) and it looks something like this:

![progress](https://i.imgur.com/gz6ppAg.png)

We should probably merge our efforts: 

- I do not like the ``process_lint`` function since it a usecase like this a bit pointless: ``rmlint -o sh | sh`` (I think we had this usecase iirc). In my implementation the progress info is written on top of the file by seeking back (if the file is seekable, if not the progress won't show).
- I think my counting is a bit simpler, I just count the lines the ``sh`` formatter outputs. I think this is somewhat more fail proof and easier to implement.
+ You have an option to dynamically disable the progress output. I would vote for making it enabled by default.

**Comment by antoniocaruso** [comment]
Perfect. :)

Il 20 mag 2017 12:16 AM, "Chris Pahl" <notifications@github.com> ha scritto:

**Comment by SeeSpotRun** [comment]
Oops looks like we crossed over.

Yes agree progress should be default - I was half thinking about backwards compatibility but that's not really relevant.

I don't really like the idea of back-seeking; maybe better to delay rmlint.sh output until the end?

Happy with the percentage indicator; it takes up less space that what I had.  Probably doesn't need the decimal place?

`rmlint -o sh | sh` doesn't seem to work on any versions atm (interpreting EOF as user interrupt?) but does work with `rmlint -o sh -s -- -d`

**Comment by sahib** [comment]
> I don't really like the idea of back-seeking; maybe better to delay rmlint.sh output until the end?

I don't like seeking that much either...

> Happy with the percentage indicator; it takes up less space that what I had. Probably doesn't need the decimal place?

For only real big runs I guess, but the extra two glyphs won't hurt I guess.

> rmlint -o sh | sh doesn't seem to work on any versions atm (interpreting EOF as user interrupt?) but does work with rmlint -o sh | sh -s -- -d

Thanks for figuring out the correct command line. I thought for some reasons we need it in the GUI, but that part is only parsing the output of rmlint. Maybe the usecase is a bit too esoteric to have it included...
I'm fine with removing it and converting to your solution, if you want to.

**Comment by sahib** [comment]
Update: I merged with your attempt @SeeSpotRun.

Points taken from you:
- No seeking back anymore, ``process_lint`` as wrapper function it is.
- Simple integer arithmetics, no call to ``bc`` or ``/bin/printf`` anymore (and no floating point).

I also cherry-picked 7c06aaae237166fae2ec60855d30ad3b0dd90c92 from your branch.
It still looks like before, minus the floating point part.

This issue can likely be closed now, please re-open if any problem persists.
