### ISSUE TITLE
Exit if invalid path given

### ISSUE THREAD

**Issue by hungrywolf27** [sahib/rmlint#227]
Thanks for this great software.

I'd suggest that rmlint should exit immediately if any of the paths given on the command line is invalid, rather than continuing to scan as it currently does. This could be overridden by a command-line option to ignore invalid paths, but I think the default behavior should be to exit so that time isn't wasted on a scan if the user made a typing error.

A related issue is that when the -g switch is given, error messages for invalid paths are not shown. Since I was in the habit of always using the -g switch to show the progress bar, it took me several minutes to realize that I had a spelling error in a pathname, because I wasn't seeing any error message. Take away the -g switch and the warning message appears.

**Comment by sahib** [comment]
Sorry, for the late answer, I was on vacations. 

Your request is making sense to me. 

Just to sum up "officially" why the current behavior is like that:
When reading paths from ``stdin`` it's somewhat okay that some of those files do not exist.
After all we might also fail for some paths that are valid but we haven't good enough permissions for.
But, yes, it's easy to miss a path typo or elsewise malformed path and I guess it's better to be consistent.

For the progressbar: In order to not distort the output the log level is set to show only critical errors when specifying the ``-g`` switch. I guess we should re-evaluate on what we call error (i.e. what the user want's to see and only block warnings and below) or at least wait until actually the start of scanning for setting the log level.

I'll put together a fix in the next days which will be in the next release.

**Comment by sahib** [comment]
Should be fixed as of b80fad3175cd91ec258644f454c205e8808bdb01 and df2e0392fe57e9bacc5278c92ba6cfbc6c711cb7. Please re-open if the original problem was not fully addressed.
