### ISSUE TITLE
[Feature Request] Filename matching wihtout hash.

### ISSUE THREAD

**Issue by timoc** [sahib/rmlint#229]
I'm trying to do some de-duplication, and i was thinking it would be great if it could match on filename, without hash. 

- For duplicate filename, options like 'word' might match testing-times.docx, 'times-testing.docx' and 'testing times.docx'. This then generates a candidate list for examination, or with sort-filtering it can keep the newest. regexp ignore rules would be nice too.
- For duplicate dir detection, as it may contain the same files, but with different hashes. Or directories with simlar filename files

**Comment by sahib** [comment]
Short answer: No.

Long answer: 
This is kind of a regular request (See e.g. the similar https://github.com/sahib/rmlint/issues/214), but I decided not to implement it for these reasons:

- ``rmlint`` is a tool that cares about content only. It has option to help you filter that content in many ways (for example filter by same basename), but no options to act upon same metadata (like paths, size etc.).
- While recognizing same filenames might be feasible, recognizing similar file names is not. There is simply no proprer definiton of what is a "similar" filename. Metrics like for example the levenshtein distance are hard to compute and might not even make sense for the usecase you mentioned. Pattern matching is provided already by other tools (see below).
- The amount of the usecases we would need to implement here is enormous (every user expects something different, because he has knowledge about his data ``rmlint`` cannot have) and it would be basically another tool built inside of ``rmlint``. Therefore we decided to make it easy to integrate such tools by piping their output into ``rmlint`` (``your-magic-tool | rmlint -``). For many usecases this tool is ``find``. It also supports the regexp ignore rules you wanted. ``rmlint`` is a tool to find files and directories with identical content and that's what it is good at. Everything else around is convenience.

Long story short, such requests are always way to undefined to be implemented and are often easier solved  using a different approach that might involve different tools alongside ``rmlint``. 

There are however some options you might want to look at:

```
-e --match-with-extension / -E --no-match-with-extension (default)

    Only  consider  those  files  as  dupes that have the same file extension.
    For example two photos would only match if they are a .png. The extension
    is compared case-insensitive, so .PNG is the same as .png.

-S --rank-by=criteria (default: pOma)

    Sort the files in a group of duplicates into originals and
    duplicates by one or more criteria. Each criteria is defined by a
    single letter (except r and x which expect a regex pattern after
    the letter). Multiple  cri‐ teria  may be given as string, where
    the first criteria is the most important. If one criteria cannot
    decide between original and duplicate the next one is tried.

    · m: keep lowest mtime (oldest)   M: keep highest mtime (newest)
```

With them you could already do something like this:

```shell
# Look in all docx files for duplicates, make rmlint validate they have the same extension and
# sort the original to be the file with the newest mtime.
$ find -iname '*.docx' | rmlint -e -S M -
```

> For duplicate dir detection, as it may contain the same files, but with different hashes. Or directories with simlar filename files

Sorry, this did not make any sense to me.
