### ISSUE TITLE
rmlint.sh: RMLINT_BINARY is set to '(null)'

### ISSUE THREAD

**Issue by hungrywolf27** [sahib/rmlint#232]
Line 5 of the generated rmlint.sh:
```
RMLINT_BINARY='(null)'
```
When running `rmlint.sh -p` this produces the following errors:
```
./rmlint.sh: line 119: (null): command not found
 ^^^^^^ Error: files no longer identical - cancelling.....
```

Further experimentation:

running `rmlint test1/ test2/` produces `rmlint.sh` with ```RMLINT_BINARY='(null)'```

but running `/usr/bin/rmlint test1/ test2/` produces `rmlint.sh` with ```RMLINT_BINARY='/usr/bin/rmlint'```

(This is 2.6.0 compiled and installed from source according to instructions)

**Comment by sahib** [comment]
Thanks for finding this.

I wrote some code that was supposed to find the full path to the own binary, but it was very simplistic and easy to break. For now it falls back to ``$(which rmlint)`` if it failed. Later on a better solution should probably use some library called [``binreloc``](https://github.com/datenwolf/binreloc). Turns out finding the path to the own binary is neither portable, nor easy.

**Comment by sahib** [comment]
As of  0f8c139f630517f0098ce956bdfcc43f2af3e822 ``rmlint`` will look at ``/proc/self/exe`` to find where it's own executable resides. This will work reliable on linux, but most likely not on other systems. There we fall back to 

Maybe as an explanation why all this hassle:
The script output needs the path to ``rmlint`` for some special commands that are hard to implement otherwise. Those are especially ``--equal`` and ``--btrfs-clone``. With the correct path we want to assure that we use a compatible ``rmlint`` version (i.e. the one that also wrote the script).
