### ISSUE TITLE
OS X: rmlint --gui fails with error message

### ISSUE THREAD

**Issue by workflowsguy** [sahib/rmlint#253]
I installed `rmlint 2.6.1`on 10.11.6 with `brew install rmlint`.
Running `rmlint --gui` gives

`Failed to load shredder: No module named 'shredder'
This might be due to a corrupted install; try reinstalling.`

**Comment by SainteCelery** [comment]
I posted about this same problem months and months ago and was told that it must be something wrong with my environment, despite *numerous* people having had the same, seemingly unresolved, issue. Dev said he had no Mac to troubleshoot with. Still impossible to use Shredder or even see what the UI looks like.

**Comment by sahib** [comment]
Hello @workflowsguy,

thanks for report. The error you're getting means that 
 Can you please provide some more info? Specifically:

- The output of ``brew install --verbose`` (to see if the GUI was actually installed)
- ``python -c 'import sys; print(sys.path)'`` 
- ``find /usr/lib -type d -iname 'shredder'``

Hello @SainteCelery,

> I posted about this same problem months and months ago and was told that it must be something wrong with my environment, despite numerous people having had the same, seemingly unresolved, issue for years. Dev said he had no Mac to troubleshoot with. No suggestions about what to look at in paths or PYTHONPATH or anything else. Reinstalled at least a dozen times. Fine-tuned paths. The issue is not my environment. And it's still impossible to use Shredder or even see what the UI looks like. The GUI should just not be listed as an option for Macs because it isn't one.

 thanks for your *nice* and *well-chosen* words, but remember that we do this for free and we do not owe you any of our time. While I somewhat understand your frustration, we're the wrong people to shout at (if there is any right person to do that) - so please calm your tone. It's hard to see for us what's happening on a platform we do not know much about and have no access to without the help from users. We know this not a nice state, but we can only properly support the platforms we're running ourselves. 

So go a few steps back, buckle up, learn about the issue and/or make someone with a Mac look at it and open a PR if you want to see this fixed as soon as possible. This is likely an issue that needs to be addressed in the homebrew formula.

**Comment by workflowsguy** [comment]
Output from `brew install --verbose rmlint`:

```
==> Downloading https://homebrew.bintray.com/bottles/rmlint-2.6.1.el_capitan.bottle.tar.gz
Already downloaded: /Users/stefan/Library/Caches/Homebrew/rmlint-2.6.1.el_capitan.bottle.tar.gz
==> Verifying rmlint-2.6.1.el_capitan.bottle.tar.gz checksum
==> Pouring rmlint-2.6.1.el_capitan.bottle.tar.gz
tar xzf /Users/stefan/Library/Caches/Homebrew/rmlint-2.6.1.el_capitan.bottle.tar.gz
==> Finishing up
ln -s ../Cellar/rmlint/2.6.1/bin/rmlint rmlint
ln -s ../../../Cellar/rmlint/2.6.1/share/man/man1/rmlint.1.gz rmlint.1.gz
/usr/bin/sandbox-exec -f /tmp/homebrew20170830-46058-16v4run.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/postinstall.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/rmlint.rb --verbose
==> Summary
🍺  /usr/local/Cellar/rmlint/2.6.1: 7 files, 318.1KB
```
Output from `python -c 'import sys; print(sys.path)'`:

`['', '/Library/Python/2.7/site-packages/pyobjc-3.0.4-py2.7.egg', '/usr/local/lib/wxPython-3.0.2.0/lib/python2.7/site-packages', '/usr/local/lib/wxPython-3.0.2.0/lib/python2.7/site-packages/wx-3.0-osx_cocoa', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/Users/stefan/Library/Python/2.7/lib/python/site-packages', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC', '/Library/Python/2.7/site-packages', '/Library/Python/2.7/site-packages/PIL', '/usr/local/lib/wxPython-3.0.2.0/lib/python2.7']`


Output from `find /usr/lib -type d -iname 'shredder'`:

-> nothing

Thanks!

**Comment by sahib** [comment]
Hello @workflowsguy,

thanks for the output. 

This line here is suspicious:

```
🍺  /usr/local/Cellar/rmlint/2.6.1: 7 files, 318.1KB
```

7 files would be way to few files to have the GUI installed (but strangely enough a bit more than I expected). Also the output of the ``find`` command fits to that. I guess very much the ``brew`` formula [over here](https://github.com/Homebrew/homebrew-core/blob/master/Formula/rmlint.rb) does not install the GUI (at least I don't see any ``install`` commands for ``gui/``). 

Maybe the original author @tomhoover can also shed some light to this and maybe estimate how much work it would be to install the python gui (or if it might even warrant an additional formula).
If it's not too much trouble, we could file an issue on the original formula.

**Comment by workflowsguy** [comment]
I was not aware that the brew formula for `rmlint` was created by someone not directly related to this project.

I have just created an issue for this: [https://github.com/Homebrew/homebrew-core/issues/17434](url)

**Comment by tomhoover** [comment]
A little history--there were two issues opened by @simmac about a year ago:

**Homebrew formula** https://github.com/sahib/rmlint/issues/175
**rmlint --gui not working on OS X** https://github.com/sahib/rmlint/issues/176

I created the homebrew formula to close #175, which simplified the installation of rmlint on MacOS. I spent a little time on #176, but as I've never been successful in using the gui on MacOS, it remained open. Since I only run rmlint from the command line, I'll admit I haven't spent much time trying to troubleshoot why I cannot run the gui on my Macbook.

I'll try to spend some time again to see if I can figure out how to run the gui on my Mac. If I cannot get the gui to work, then there's no way for me to know how to revise the homebrew formula to install the gui components (a catch 22). If someone knows how to successfully install/run the gui, maybe they can assist in revising the homebrew formula for rmlint?

**Comment by sahib** [comment]
> I created the homebrew formula to close #175, which simplified the installation of rmlint on MacOS. I spent a little time on #176, but as I've never been successful in using the gui on MacOS, it remained open. Since I only run rmlint from the command line, I'll admit I haven't spent much time trying to troubleshoot why I cannot run the gui on my Macbook.

Riiight, I totally forgot about #176. 

> I'll try to spend some time again to see if I can figure out how to run the gui on my Mac. If I cannot get the gui to work, then there's no way for me to know how to revise the homebrew formula to install the gui components (a catch 22). If someone knows how to successfully install/run the gui, maybe they can assist in revising the homebrew formula for rmlint?

:+1: 

If the errors are not too Mac-specific, I can try to help also.

**Comment by workflowsguy** [comment]
Great!
While I know nothing about "git", "gists" or "pull requests", if there is anything else I can do to help you, I gladly will.

**Comment by Master-MD** [comment]
okay I do have the same problem...

Admins-Mac-Pro:~ admin$ rmlint --gui
Failed to load shredder: No module named 'shredder'
This might be due to a corrupted install; try reinstalling.

are any fixes in near future planed?

**Comment by zzkt** [comment]
I had a quick look at this, and it appears the version of `rmlint` installed via homebrew doesn't include dependencies for the gui (as of 2.9.0) Installing from source and installing dependencies manually leads to the same issue.

Since the gui interface requires `polkit` (which is not currently working on macos) it's probably not a simple change to get it working...

so...
`brew install rmlint pygobject3 gtk+3 dbus`

then...
`pip3 install pycairo`
`pip3 install PyGObject`
`pip install dbus-python`

...gets to the point where installing `pypolkit` will fail as polkit (etc) wont build.

**Comment by CouldBeThis** [comment]
Hello, 

I am not sure if this is of any value, or perhaps the outcome is implicit in the already available information. 

However I attempted to compile on Mac according to instructions found here [Installation Compilation — rmlint (2.8.0 Maidenly Moose) documentation](https://rmlint.readthedocs.io/en/latest/install.html#compilation). Steps:

```sh
# uninstall brew version
brew uninstall rmlint
# clone git repo (stable branch) & go into the directory
git clone https://github.com/sahib/rmlint.git
cd rmlint
# configure/check `scons`
scons config
# run installer
sudo scons --prefix=/usr install
```

`scons` printed an output free of any obvious errors. I can post if it would be of any value (but it's long). But it ended 

```sh
==> OK!
scons: done building targets.
```

`rmlint` seems to run (didn't do much testing), but `rmlint --gui` returns same error as for previous users:

```sh
Failed to load shredder: No module named 'shredder'
This might be due to a corrupted install; try reinstalling.
```

After that I saw the [previous note](https://github.com/sahib/rmlint/issues/253#issuecomment-627251124) about `polkit` not being available on Mac. The `scons` output didn't mention `polkit` or `pkexec`. In case there was some change in status in the year since that was posted, I tried to investigate this a bit. 

Because I am stubborn I tried to isntall [pypi `pypolkit`](https://pypi.org/project/pypolkit/) but of course that didn't work. I think it's looking for `polkit-dbus` and `polkit-grant` 

Poked around with no useful result in:

- polkit: [GitLab](https://gitlab.freedesktop.org/polkit/polkit), [wikipedia](https://en.wikipedia.org/wiki/Polkit), [docs](https://www.freedesktop.org/software/polkit/docs/latest/polkit.8.html), manpage [polkit(8)](https://www.mankier.com/8/polkit) and [pkexec(1)](https://www.mankier.com/1/pkexec)
- brew: [formula](https://formulae.brew.sh/), [org github](https://github.com/Homebrew/)
- fink: [package database](https://pdb.finkproject.org/)

*But then* turned up [policykit via MacPorts](https://ports.macports.org/port/policykit/summary). (Apparently only [58 users](https://ports.macports.org/port/policykit/stats?days=30&days_ago=0) have installed this ever. Which doesn't bode terribly well.)

I'm not a regular macports user and installing this package took almost an hour as macports did all sorts of things to my system, looks like most of them involve fiddling with python. I hope it didn't hose the mostly functional set up I've managed to create. So at the end of it, `polkit` was apparently installed. But it did not make any difference:

- uninstalled/reinstalled `rmlint` via `scons` = no change
- retried `pypolkit` install = no change 

Searched my system drive for anything to do with `polkit-dbus` or `polkit-grant` without results, though I do now have various directories under `/opt/local` with related files. 

So this is as much as I can think of to do, and I end with the same conclusion as everyone else, which is that at the moment it's not possible.

**Comment by SeeSpotRun** [comment]
I'm pretty sure the gui can be run without polkit: https://github.com/sahib/rmlint/blob/427791ca7c9ffa66b2c666b6b01874c5e165fae6/gui/shredder/views/editor.py#L25-L28

Polkit is only used for enabling root from the gui.

...although would have to delete this line:
https://github.com/sahib/rmlint/blob/427791ca7c9ffa66b2c666b6b01874c5e165fae6/gui/shredder/__init__.py#L11


 ###  Back to your error message:
> Failed to load shredder: No module named 'shredder'
This might be due to a corrupted install; try reinstalling.

This looks more like a PYTHONPATH issue.  Try the workaround at https://github.com/sahib/rmlint/issues/171#issuecomment-189950699
> 
```
# This is only temporary, put this in .bashrc if you want it persistent:
$ export PYTHONPATH=$PYTHONPATH:/usr/lib/python3.4/site-packages/
```

Replace `/usr/lib/python3.4/site-packages/` with the path mentioned during `sudo scons --prefix=/usr install`, it should be something like `Writing /usr/local/lib/python3.9/site-packages`.

Also you might want to delete the Polkit requirement line in `gui/shredder/__init__.py` before running `scons`.

**Comment by SeeSpotRun** [comment]
Develop branch now has the above issues (Polkit dependency, PYTHONPATH) resolved.

Updated `homebrew` formula is [in progress ](https://github.com/SeeSpotRun/homebrew-core/blob/rmlint/Formula/rmlint.rb); new `MacPort` [formula](https://github.com/SeeSpotRun/ports/blob/main/sysutils/rmlint/Portfile) also in progress.  Will request official formula updates for both after next `rmlint` release, planned for June.

Closing issue.  Thanks all for the feedback.

**Comment by rafo** [comment]
More than a year later: if there is something blocking the way for a GUI on MAC, how  about an issue with a "help-wanted" tag?

**Comment by mag911** [comment]
Got the GUI going under macOS 12.6 (sort of). Install rmlint with brew. Download the rmlint source code from here (Github). Grab a terminal and cd into the gui source code folder. Issue 'make run' on the command line. Things will fail. Issue 'brew install pygobject3' to get access to 'gi'. Then 'brew install gtk+3' and 'brew install librsvg'. Within the __init__.py file, comment out two lines: gi.require..Polkit and gi.require..GtkSource. Issue make run on the command line and the GUI should start. It's not 100% perfect visually but it does seem to function perfectly.

**Comment by Cebtenzzre** [comment]
@mag911 You'll need to install gtksourceview3 and put back the GtkSource line to be able to preview rmlint.sh scripts. If you go through the trouble of downloading from source you may as well download the latest [develop version](https://github.com/sahib/rmlint/archive/refs/heads/develop.zip) and run `python3 setup.py install --user` in the gui directory. I can't guarantee compatibility between versions so you should probably build rmlint from the develop branch as well.

**Comment by mag911** [comment]
@Cebtenzzre cheers for the heads up. Script preview was working, because gtksourceview was installed, just not gtksourceview3. When I install gtksourceview3 .. it's a much nicer looking preview, so thanks heaps! 👍🏼😀

**Comment by dzg** [comment]
Another year ... any progress for solid GUI on Mac Silicon? 
Thanks!!

**Comment by Cebtenzzre** [comment]
@dzg What is the problem you are experiencing? If you want there to be a homebrew or macports package for it, you'd have to ask if either team would be willing to create and maintain one - I don't own a Mac, and rmlint has no other active developers at the moment. If you are having trouble building the GUI from source, please open a new issue.

**Comment by patmuk** [comment]
Happy 2024!

I wonder if there an easy solution for MacOS (I am on Sonoma) to install rmlint with UI. Or otherwise, if this ticket could be re-opended.

I get the same error as the OP:

```
After
brew install rmlint
```
I get
```
rmlint --gui
Failed to load shredder: No module named 'shredder'
This might be due to a corrupted install; try reinstalling.
```

The proposed solution is rather a workaround:
> Got the GUI going under macOS 12.6 (sort of). Install rmlint with brew. Download the rmlint source code from here (Github). Grab a terminal and cd into the gui source code folder. Issue 'make run' on the command line. Things will fail. Issue 'brew install pygobject3' to get access to 'gi'. Then 'brew install gtk+3' and 'brew install librsvg'. Within the **init**.py file, comment out two lines: gi.require..Polkit and gi.require..GtkSource. Issue make run on the command line and the GUI should start. It's not 100% perfect visually but it does seem to function perfectly.

And installing from source is not the solution IMHO as well:
Doing this is not the problem - but the potential pitfalls are too many for a normal user, even for a developer who just wants to use this tool. This only works if the right toolchain is set up, which is challenging especially in python.

Is there a smooth way to install the UI for MacOS (I am on Intel)?

**Comment by cebtenzzre** [comment]
> Is there a smooth way to install the UI for MacOS (I am on Intel)?

You could ask the homebrew or MacPorts team to package rmlint-shredder, or contribute a formula/port yourself. We don't ship binaries and don't intend to start doing so anytime soon.
