### ISSUE TITLE
Deliver in package form

### ISSUE THREAD

**Issue by pabloab** [sahib/rmlint#254]
Would be great to have rmlint on package form. This could be .deb, Snap, Flatpack or [appimage](appimage.org). In my case on Ubuntu 16.04 still isn't on official repo.

**Comment by sahib** [comment]
A ``.deb`` was already built for Debian (See #143). Currently it's only available in the debian unstable repos (sid). But eventually it will wander to debian stable and some distant day ubuntu folks will likely pick it up.

I don't know very much about ``snap`` and ``flatpak``, but afaik they are sandboxed packages and that does not really make sense for something like ``rmlint``. ``AppImage`` may be possible, but still people will search their package manager first and then ``rmlint``'s documentation. So the proper solution would be to wait & I'd prefer people to compile themselves in the meantime instead of putting in more maintaining time.
