### ISSUE TITLE
Compare text files with dissimilar line endings

### ISSUE THREAD

**Issue by nrbray** [sahib/rmlint#262]
What is the easiest way to allow text files to match when their line endings as e.g. reported by Meld, Files are identical except for differing line endings: UNIX (LF) == DOS/Windows (CR-LF)?

**Comment by SeeSpotRun** [comment]
Not possible with `rmlint` sorry.

If you just want to know if two files are identical you can do it with diff:
```
diff --strip-trailing-cr <file1> <file2> >/dev/null && echo "same" || echo "different"
```
We could in theory add a feature to do it, but it would be messy because `rmlint`'s algorithms are set up and optimised based on treating all files as binary data.

New algorithm would be:
1. Find files (no change to existing code)
2. Calculate checksum of all files after first normalising line endings (new code)
3. Find matching checksums (new code)
4. Output matches (no change to existing code)

How important is this usecase?  Would you also want to normalise other whitespace (space, multiple spaces & tabs all treated the same)?

**Comment by sahib** [comment]
You could also use the -Q option to ignore the last two bytes of the file. That is of course not an exact solution, but might be good enough. (I'm on the phone, so no example. Just read the docs. ;-))Am 09.11.2017 9:05 nachm. schrieb Daniel T <notifications@github.com>:Not possible with rmlint sorry.
If you just want to know if two files are identical you can do it with diff:
diff --strip-trailing-cr <file1> <file2> >/dev/null && echo "same" || echo "different"

We could in theory add a feature to do it, but it would be messy because rmlint's algorithms are set up and optimised based on treating all files as binary data.
New algorithm would be:
Find files (no change to existing code)Calculate checksum of all files after first normalising line endings (new code)Find matching checksums (new code)Output matches (no change to existing code)
How important is this usecase?  Would you also want to normalise other whitespace (space, multiple spaces & tabs all treated the same)?

**Comment by sahib** [comment]
I think we can close this, since no more discussion is apparently happening here.
Feel free to re-open in case of news.
