### ISSUE TITLE
Add support for SnapRAID checksums

### ISSUE THREAD

**Issue by GitHubGeek** [sahib/rmlint#268]
[SnapRAID](http://www.snapraid.it/) is a popular FOSS utility for making "snapshot" style RAID, as well as protection against bit rots.

As part of SnapRAID's operations, a content file is created containing checksums, timestamps, file sizes and other metadata of all files protected by SnapRAID.

It would be great if `rmlint` is able to read from SnapRAID's metadata to identify duplicated files. Thanks.

**Comment by sahib** [comment]
Hello @GitHubGeek,

you forgot to add a small detail: The actual problem you want to solve. Are you hoping to increase ``rmlint``'s performance? If so, is current performance a problem or would this be more like a "nice-to-have"?

A workaround would be to write a script that exports data from the snapshots and writes the checksums to the xattr of each file. Those can then be read by ``rmlint`` via ``--xattr-read``. If you're willing to implement that, we can talk about the details.

Anyways, I'd really favor to not implement a direct bridge in ``rmlint`` for ``snapraid`` (although it's a good tool). Simply because there are many tools out there writing checksums and I really do not want to write importers for them all, even if they would be handy for a few users.

Go convince me. :smirk:

**Comment by GitHubGeek** [comment]
Thansk for the quick reply @sahib. Use case would be tens of TB's of data across many HDDs.

With such setup, `find /mnt -type f` alone would take many minutes. I imagine reading xattrs would be the same, if not slower.

If `rmlint` were able to parse SnapRAID's content file, all it takes is to parse one single file - irrespective of the no. of filesystems - to get all the metadata. Typical size of the content file is a few GBs. No need to traverse the dir tree at all.

I agree direct bridges aren't maintainable in the long run. Perhaps `rmlint` can publish and support a file format that'd allow external metadata in a single file?

**Comment by sahib** [comment]
Hello @GitHubGeek, 

> With such setup, find /mnt -type f alone would take many minutes. I imagine reading xattrs would be the same, if not slower.

I have to be persistent and ask if running ``rmlint`` is really a performance bottleneck. Did you try?
Also keep in mind that ``rmlint`` is capable of only re-checking files newer than a certain mtime and/or writing a json file that can be used to ``--replay`` results later on. I'm getting the feeling that you have a valid problem but need a different solution than the oddly specific one you proposed....

> If rmlint were able to parse SnapRAID's content file, all it takes is to parse one single file - irrespective of the no. of filesystems - to get all the metadata. Typical size of the content file is a few GBs. No need to traverse the dir tree at all.

Blasphemic question then: What do you need ``rmlint`` for then? :smirk:
As converter of the duplicate pairs to a shell script?

> I agree direct bridges aren't maintainable in the long run. Perhaps rmlint can publish and support a file format that'd allow external metadata in a single file?

We kinda had this for some time (``--cache``). It was a sqlite database and the usecases was more thought to be a caching layer after the first run. In the end we decided to remove it, due to the added complexity and small plus in features it gave us. Most of all the performance also wasn't much better than a normal run and sometimes even worse.

It was then replaced by the ``--replay`` feature which reads a ``.json`` file (containing paths and hashes) and outputs them without any I/O involvement. If you manage to export your snapraid file to a ``.json`` you'd have what you proposed....
