### ISSUE TITLE
Consider posix_fadvise DONTNEED to avoid unnecessary page caching during scan

### ISSUE THREAD

**Issue by jcharaoui** [sahib/rmlint#286]
When scanning a large dataset for duplicates, rmlint causes the kernel page buffer to fill up with content from this dataset, thus possibly pushing out better data that is already in the buffer and/or causing some application pages to be swapped out.

Something similar to [nocache](https://github.com/Feh/nocache) but integrated into rmlint.

**Comment by sahib** [comment]
Hello @jcharaoui,

you proposed a solution, but you didn't really mention the problem.
What is it that you are trying to solve?

> [...] pushing out better data [...]

What is *better*? Data that you're currently working on?

``rmlint`` is using ``posix_fadvice`` - but we use it to tell the operating system to [read ahead data it will need in the near future](https://github.com/sahib/rmlint/blob/master/lib/hasher.c#L171) in order to maximize it's performance and not to be nice to other application's caches.

I think there are better ways to do what I think you want to do. ``nocache`` might be one of them.

**Comment by jcharaoui** [comment]
The problem is that I have a very big dataset, and not so much total memory. After running for some time, doing it's thing (eg. fileserver serving files...) the page cache is populated with lots of data which is useful for its current workload. I think that running `rmlint` in a way that doesn't disturb that cache would be useful, perhaps at the expense of speed.

Backup programs like [borgbackup](https://github.com/borgbackup/borg/blob/50e1759460912b43e93371a98922fdd1939b6acd/src/borg/_chunker.c#L196-L200) employ such a mechanism to avoid disturbing the page cache while scanning seldom-needed files for changes.

I haven't tried `nocache` but I doubt it would be as fast as a native implementation.

**Comment by sahib** [comment]
Hello @jcharaoui,

I'm still not very convinces, but I pushed a small experiment to the [feature/fadvise-forget branch](https://github.com/sahib/rmlint/tree/feature/fadvise-forget). Maybe you can play around a bit with it and see if it helps your usecase. It directly tells the kernel to forget about the data he already read.
