### ISSUE TITLE
feature request : skip hashing altogether

### ISSUE THREAD

**Issue by michaelcinquin** [sahib/rmlint#321]
I would like to put rmlint to use accross slow network connexions. 

In my use case, if files have same name, ctime, mtime and filesize, they are duplicates, I don't need to do any hash checking on them.

Could we have an option to skip hash-checking altogether?

thanks!

**Comment by sahib** [comment]
We could in theory, but I'd rather decline this request.  Mostly due to the following points:

* This changes the meaning of "duplicate". Before it was content wise, now metadata would play a role. What metadata is used is a matter of discussion too - other user might prefer a different set of fields.
* ``rmlint`` is really good at checking content in a fast way. It is and shouldn't be an extended ``find`` of sorts that tries to solve every possible use case. I think your task is easier solved by writing a script to do that.

The solution regarding slow network is from my experience: Somehow do the deduplication on the remote machine itself. Sorry, if that sounds too obvious... If you're really stuck with a remote filesystem, writing a script to do your task will be faster than squeezing ``rmlint`` into this use case.
