### ISSUE TITLE
Fedora 29 COPR

### ISSUE THREAD

**Issue by pwd-github** [sahib/rmlint#326]
Hiya, wondered if you wouldn't mind enabling the copr for Fedora 29?

**Comment by sahib** [comment]
Hello @pwd-github,

I don't maintain COPR anymore. I'm rather hoping that it comes to the official fedora repos and someone picks it up to include it there. Since I don't use Fedora anymore myself, I have to rely on users doing that. There's already a ``.spec`` file for building a ``.rpm`` [that only needs small adjustments](https://github.com/sahib/rmlint/blob/master/pkg/fedora/rmlint.spec) regarding the version number.

**Comment by eclipseo** [comment]
https://copr.fedorainfracloud.org/coprs/eclipseo/rmlint/

Fedora Request:
https://bugzilla.redhat.com/show_bug.cgi?id=1655338

**Comment by sahib** [comment]
@eclipseo: Thanks a lot. I changed the fedora package link in the docs to point at your page. Also updated the ``spec`` file in ``pkg/fedora/rmlint.spec``.

Time to delete my copr account.  :tada:

**Comment by sahib** [comment]
@eclipseo: I saw that the package was approved. Great! Thanks for the effort.

Can I close this issue?

**Comment by eclipseo** [comment]
Yes thank you, I've built it on Fedora 28 to 30.
