### ISSUE TITLE
add an option to detect if file was modified

### ISSUE THREAD

**Issue by CdeMills** [sahib/rmlint#334]
Hello,
I'm working on embedded systems, and I would like to ensure that data stored on SD cards are not modified, either inadvertently (not using the right API), either because the SD card experience issue, either because of errors during network transfer

Would it be possible to add some switch to unconditionally add the checksum in the xattr field, irrespective to the fact that the file seems duplicated or not ? the "-U" flag seems to not add such field for all files.

In a latter stage, the validity of a file could be verified w.r.t. its original checksum

Regards

Pascal

**Comment by sahib** [comment]
Please elaborate. I.e. provide a valid use case, explain how it would help you and why you can't do that with the existing options.

**Comment by sahib** [comment]
Thanks for elaborating.

> Would it be possible to add some switch to unconditionally add the checksum in the xattr field, irrespective to the fact that the file seems duplicated or not ? the "-U" flag seems to not add such field for all files.

Yes, ``-U`` only adds this field to files that ``rmlint`` decides to hash. Those files have to fulfill some prerequisites, including have the same size as a bunch of other files and more, depending on other options. This information is mainly useful for ``rmlint`` itself, since it can be used for caching purposes.
It was meant to be data that is read only by ``rmlint``, and is not targeted for third-party consumption - especially since those hashes **are not guaranteed to be unique per file**. They are unfinished, which means that the part that comes after stopping the checksum process might still be totally different.

It would be likely possible to add such an option (calculate checksums till the end) - but I'd argue that this kind of feature is out of scope for a tool like ``rmlint``. This is a job either for the file system or another program targeted for your use case.

**Comment by sahib** [comment]
I'll leave this open for now, in case you have something to add.

**Comment by CdeMills** [comment]
Hello,

sorry for the delay, I've had a few very busy days

Basically I would like to have some method permitting to ensure that, on
volumes doing long term storage, the file content is still OK and did not
suffer from some kind of modification due to the storage mechanism failure.

Up to now I worked with one file per dir with the RC5 checksum of each
file; but having the checksum embedded into the extended attributes would
be a more elegant solution.

Do you think this could become a functionality of rmlint ?

Regards

Pascal

Le mer. 23 janv. 2019 à 10:30, Chris Pahl <notifications@github.com> a
écrit :

**Comment by sahib** [comment]
Hello @CdeMills,

what kind of file system are you using? Some "modern" file systems have this property of data checksums. ``btrfs`` comes to mind, ``zfs`` is probably quite tough for embedded environments. Also ``ext4`` seems to have [gained such an ability](https://serverfault.com/questions/456319/how-to-get-checksum-data-integrity-on-ext4). After all, this feels like something the file system could do a lot better than ``rmlint`` and on a block level.

> Do you think this could become a functionality of rmlint ?

I don't see rmlint as a consistency checker. So probably rather a no. What you want is a (fast) checksum calculator. Luckily ``rmlint`` has this built-in: Look into the ``--hash`` option (see ``rmlint --hash --help``). You should be able to wire this together with some bash scripting that creates a consistency file for each directory. The only improvement here though that ``rmlint --hash`` might (and I'm not even sure about that) faster than other checksum utilities when handling multiple files.

**Comment by CdeMills** [comment]
Hello,

I use ext4fs, indeed, but on CentOS. E2fstools is version e2fsprogs-1.42.9-13.el7.x86_64, and the checksum feature was introduce 1.43. So my guess is to wait for CentOS 8, probably around July 2019. 

Regards

Pascal
