### ISSUE TITLE
ETA jumps around wildly, e.g. from 200 days to 10 hours, and takes longer than expected to settle down

### ISSUE THREAD

**Issue by jim-collier** [sahib/rmlint#343]
This presumably isn't a bug. And not even a feature request. More of feedback on "expectations vs. observed output".

After, say, five minutes of running, I'd think it would start converging on some number, and change ever more slowly as it goes along. Presumably, the ETA is based on some algorithm like:

`++runningFileCount  //As each file is finished processing`
`projectedETA = startTime+(((now()-startTime)/runningFileCount)*totalFileCount)`

The ETA does seem to start settling down eventually so presumably there is some kind of running average going on, but given similar ETA calculations in other programs, and considering that it's chewing through files at a pretty good clip and should build up enough calculation data pretty quickly, it seems like it takes much longer for the wild swings to settle down than it "should", even if file sizes vary wildly.

**Comment by sahib** [comment]
Might be due to some changes lately. Need to investigate.

**Comment by sahib** [comment]
This commit here e8941a03dff51a86d7f74c9a10280a0c147826c1 should improve the situation a bit. Previously the throughput speed was determined by looking at the remaining bytes. This also included bytes that were simply skipped since part of the file already did not match. Now it is based on the bytes read in average in a certain time interval. Should be a bit smoother, although a little more pessimistic.
