### ISSUE TITLE
Feature request: output all files checked

### ISSUE THREAD

**Issue by spott** [sahib/rmlint#348]
It would be nice to have a flag to make the JSON file (probably the CSV as well) include all files *looked* at, annotated as "unique" if the file is unique.

My use case of this is to copy one version (including if that version is unique) of every (image) file within a directory to a new directory (sorted into folders by year and month using the EXIF data).

At the moment, this would require modifying the output python script to read both the output from `rmlint`, the output from `find`, merging the two outputs, and then removing the `original=false` files from that list... *then* copying all those resulting files.  While not really impossible, or even *super* hard, a flag that made rmlint return all the unique files, as well as those files that are dupes, would make the whole thing much easier.  I can't imagine that I'm the only one who would find this useful.

From #135, it appears that this might be at least partially done already by `-U`, but the description of `-U` says "Note that this will not include all files that `rmlint` traversed, but only the files that were chosen to be hashed."

What causes a file to be one that `rmlint` didn't hash?  A unique file size?  Is there a way to include all files traversed, with some combination of `-U` and other flags?

**Comment by sahib** [comment]
Well, not exactly impossible indeed:

```bash
$ comm -3 <(find $(realpath $YOUR_DIR) -type f | sort) <(rmlint -T df $YOUR_DIR -o json | jq -r '.[1:-1][] | select(.is_original | not) | .path' | sort) | tr -d '\t'
# List of unique files (including originals) built from find by subtracting the duplicate files.
```

> would make the whole thing much easier.

...but I get your point.

> I can't imagine that I'm the only one who would find this useful.

It's not the most asked much feature, but it pops up sometimes. Quite often people want to different things with unique files or the set of duplicates that differ slightly. That's why we write ``rmlint.json``. In conjunction with ``jq`` it makes scripting really easy. Since unique files are not really "lint" we don't handle it like lint though, but as by-product. Try this for example:

```bash
$ mkdir t
$ echo x > t/1
$ echo x > t/2
$ echo y > t/3
$ rmlint -o uniques t
/home/sahib/dev/rmlint/t/3
```

Also with the ``uniques`` output you still need to combine unique files and unique files.
I can't blame you for not reading about it in the docs though - seems it's missing there. How embarrassing. An example usage for unique might for example be:

```bash
$ rmlint t -o json -o uniques:unique_files |  jq -r '.[1:-1][] | select(.is_original) | .path' | sort > original_files
$ cat unique_files original_files
/home/sahib/dev/rmlint/t/3
/home/sahib/dev/rmlint/t/1
```

I should probably add some examples of ``jq`` to the documentation.

> From #135, it appears that this might be at least partially done already by -U, but the description of -U says "Note that this will not include all files that rmlint traversed, but only the files that were chosen to be hashed."
> 
> What causes a file to be one that rmlint didn't hash? A unique file size? Is there a way to include all files traversed, with some combination of -U and other flags?

``-U`` doesn't really help you here. It is really only about files that reached the hashing phase.
Unique file size is one of the many reasons to break out before. Options like ``--match-basename`` or ``--no-followlinks`` might as well filter the output before it comes to hashing. ``-U`` is only helpful for caching checksums to avoid duplicate work.

**Comment by spott** [comment]
Thanks for the quick response.  this helps a lot:

>`
$ rmlint t -o json -o uniques:unique_files |  jq -r '.[1:-1][] | select(.is_original) | .path' | sort > original_files
`

`jq` looks pretty powerful, I'll have to play with it some more.  Thanks for the one liners.

I still think things would probably be easier for certain workflows if there was a flag that would add unique files to the json output.

> Quite often people want to different things with unique files or the set of duplicates that differ slightly.

I imagine these different things would be easily dealt with using various fields of the json record for each unique file, and the 'type' flag of 'unique' would nicely separate.  On the other hand, I understand that this functionality is technically present, and adding support to add it to the json files might not be worth doing.

**Comment by sahib** [comment]
> I still think things would probably be easier for certain workflows if there was a flag that would add unique files to the json output.

I can add a formatter option (``-c json:unique``) if you find a workflow example that is being made easier by this.

**Comment by sahib** [comment]
I forgot to mention that there is a ``unique`` option for the ``json`` (and also ``csv``) formatter as of 95d1d96b26dcfa61c17778354ea8c2486b57d14c.
