### ISSUE TITLE
Consider using libb2

### ISSUE THREAD

**Issue by eclipseo** [sahib/rmlint#352]
Consider using libb2 https://github.com/BLAKE2/libb2 instead of maintaining a BLAKE2 implementation in your code.

**Comment by sahib** [comment]
That is a sensible idea. We did go for embedding since there was no library available at that time that supported BLAKE2 on many distributions (including maxOSX and FreeBSD!). At least on my Arch I can see that ``libb2`` is still only in the [AUR](https://aur.archlinux.org/packages/libb2) and not in the official repositories. 

Since we don't want the burden of installing weird dependencies for our users, I won't change this for now. I add a reminder for myself to check again in a year.
