### ISSUE TITLE
Files with broken user or group id

### ISSUE THREAD

**Issue by cristiantod** [sahib/rmlint#379]
Hello,
Is for the first time I am using rmlint and after the first run I received a lot of baduid errors,
Is there anybody who can explain me what this mean? What a bad ID is and are there any issues related with this?
Thank you.

**Comment by sahib** [comment]
Hello @cristiantod,

bad ids mean that files have a user id (which you see as third column when you do ``ls -l your-file``) that does not correspond to an actual user on your system. This mostly happens when you copy files e.g. via fat32 formatted usb stick between systems. It's not a problem of ``rmlint``, it just shows you that you have those kind of files on your filesystem. You can search only for duplicates by doing ``-T df`` - see also the manpage for more info (``man rmlint``).

**Comment by cristiantod** [comment]
Hello,
Thank you very much for you replay. This been very helpful.
Thanks for a great tool!
