### ISSUE TITLE
Support for APFS deduplication

### ISSUE THREAD

**Issue by valenokk** [sahib/rmlint#421]
Thank you for your wonderful tool. 
Will it be hard to support APFS deduplication? macOS support clonefile(2) system call since 10.12, which lets to deduplicate in a similar way as btrfs. 

I think I can work on PR, but frankly I don't have much experience in open-source development.

**Comment by sahib** [comment]
Hello @valenokk,

adding support for APFS would be certainly possible, but I can't really do it on my side since I have no apple machine to test on. There are a few things you need to do:

* Add ``apfs`` here: https://github.com/sahib/rmlint/blob/2a4443d1b8129736adee5edc354e80e5f12be598/lib/utilities.c#L582 
* Implement the actual call to ``clonefile(2)`` here: https://github.com/sahib/rmlint/blob/2a4443d1b8129736adee5edc354e80e5f12be598/lib/session.c#L207
* Check if this works for ``apfs``: https://github.com/sahib/rmlint/blob/2a4443d1b8129736adee5edc354e80e5f12be598/lib/utilities.c#L1161
* ...possibly more.

[Here](https://rmlint.readthedocs.io/en/latest/developers.html) is some general intro on how to work on changes for ``rmlint``.

**Comment by sahib** [comment]
Closing for now. Please re-open when there are news.
