### ISSUE TITLE
"WARNING - Added big file" and "rmdir" messages in terminal on raspberry

### ISSUE THREAD

**Issue by james-cook** [sahib/rmlint#434]
Hallo rmlinters,
I've been using rmlint on Ubuntu WSL W10 exhaustively and it has been working very well :)
Today I tried it on Raspberry Pi 4 with 4GB RAM.
I compiled 2.10.1 so that my versions on all machines are the same.
I'm SSHing to the pi using an ethernet cable from a macbookair to compile and run rmlint.

When I run rmlint the command output does not have the same curses control showing progress - any (probably obvious) tip to get this working (macos terminal)?

My main problem though is that I'm getting unfamiliar messages in the terminal.
`"WARNING: Added big file "<filename (video file)>"
`
and then later on (again in the terminal):
```
# Empty dir(s):
    rmdir '/srv/XXXX... etc.
```
I killed rmlint at this point - unsure if it was actually executing the command which appears in red letters.
rmlint.sh contains the actual remove commands for these exact same directories
```
    402 ######### START OF AUTOGENERATED OUTPUT #########
    403 
    404 handle_emptydir '/srv/XXXX etc.
```

Should I just let the job continue?
Should I worry/do something about the "Added big file" message?

**Comment by sahib** [comment]
> When I run rmlint the command output does not have the same curses control showing progress - any (probably obvious) tip to get this working (macos terminal)?

Not sure if I understood this. Please describe what exactly is not working.

> My main problem though is that I'm getting unfamiliar messages in the terminal.
"WARNING: Added big file "<filename (video file)>"
and then later on (again in the terminal):

You can most likely ignore them. I turned those message to an info now, since it's not actually a warning.
This only happens when opening files bigger than 2GB on 32-bit platforms (which can cause problems with some programs).

> I killed rmlint at this point - unsure if it was actually executing the command which appears in red letters.
rmlint.sh contains the actual remove commands for these exact same directories

[It only prints what it does, it never modifies the filesystem itself](https://rmlint.readthedocs.io/en/latest/tutorial.html#beginner-examples):

```
Despite its name, rmlint just finds suspicious files, but never modifies the filesystem itself. Instead it gives you detailed 
reports in different formats to get rid of them yourself. These reports are called outputs. By default a shellscript will be written to 
rmlint.sh that contains readily prepared shell commands to remove duplicates and other finds,
```

So just let it run and use the generated script to actually remove the stuff.

**Comment by james-cook** [comment]
Thanks for your reply.
I directed stderr to a local file and this seems to work when I'm using an external ext4 drive only - i.e. I see the usual progress information with moving bars on the left (this is what I meant by "curses" - old school cursor control(!))

My current observation is that on raspi4 when using the command with external ntfs drives I don't get the usual progress output. (Again I have redirected stderr). The job itself is currently running and the disks are turning.  I'll wait to see if I get an end report and rmlint.sh.

Raspbian IS 32bit so I will have to think about the consequences before running any rmlint.sh jobs.
Warning about this is a GOOD idea!

**Comment by james-cook** [comment]
Actually...
I CAN avoid the messages by placing the rmlint command in a bash script  file and call:
./cmd.sh 2>stderr.txt

this way I do see the progress output as before

**Comment by sahib** [comment]
> Raspbian IS 32bit so I will have to think about the consequences before running any rmlint.sh jobs.
Warning about this is a GOOD idea!

Well, not so much when it worries users. ``rmlint`` can handle big files on 32 bit just fine (although that might take a while on a pi :smirk: ), therefore it should be a just info for the user. It was a warning, because we had some issues back then, but they should be resolved.

> My current observation is that on raspi4 when using the command with external ntfs drives I don't get the usual progress output. (Again I have redirected stderr). The job itself is currently running and the disks are turning. I'll wait to see if I get an end report and rmlint.sh.

You can try running ``rmlint`` with ``-vvv`` as only output to see if it actually doing something. Maybe it's stuck because of something weird.

> I CAN avoid the messages by placing the rmlint command in a bash script file and call:
./cmd.sh 2>stderr.txt

That sounds weird. Do you see it when you don't redirect stderr?

**Comment by james-cook** [comment]
`That sounds weird. Do you see it when you don't redirect stderr?`
...you are right, I don't need the redirect.

I'll look again at this later on. I was under the impression the command behaves differently on the raspberry compared to w10 (as far as output is concerned). But before anyone else starts double checking I better double check this myself.

**Comment by SeeSpotRun** [comment]
@james-cook can this issue be closed?
