### ISSUE TITLE
Multilevel hashing

### ISSUE THREAD

**Issue by jonjonw** [sahib/rmlint#441]
I was thinking, hashing by file size before running a hash algorithm speeds things up significantly. Large files could potentially be sped-up with a fast partial hash before a full hash.

You could chain the checks in the algorithm parameter, so something like:
`rmlint -a=xxhash_16k:xxhash_-16k:blake2b`

would hash the files first by size, then by the xxhash on the first 16k of each file (if their sizes match), then the xxhash of the last 16k (if all the previous hashes match) and finally if all the previous hashes match then run blake2b on the entire file.

**Comment by sahib** [comment]
That's how the ``rmlint 1.0.0`` (somewhen around 2010 :smile:) worked. This worked okay, but back then we had still mostly rotational disks where this approach failed due to expensive seeks. Current versions it also checks the file size, but then it does incremental, parallel hashing which turned out to be a generally good approach for most data sets. Also it allows some more optimizations as [described here](https://rmlint.readthedocs.io/en/latest/developers.html#optimizations).
