### ISSUE TITLE
scons instal should not ship /usr/share/glib-2.0/schemas/gschemas.compiled

### ISSUE THREAD

**Issue by lockywolf** [sahib/rmlint#445]
This is a bug in the most recent release, 2.10.1.

Building and installing the program like this:

```
scons config
scons -j 4
scons --prefix=${PKG}/usr install
```
creates a file `${PKG}/usr/share/glib-2.0/schemas/gschemas-compiled`. 
It should not do so, this file may be generated by a post-install script, or something like this, I am not sure, but if done like it is done, the file overwrites the system one and most glib-2 apps stop working.

**Comment by sahib** [comment]
Yeah, I think that's a little more complicated.

> [...] creates a file ${PKG}/usr/share/glib-2.0/schemas/gschemas-compiled.
> It should not do so, this file may be generated by a post-install script, or something like this.

The install steps runs the following command:

```
# PREFIX is ${PKG}/usr in that case.
glib-compile-schemas ${PREFIX}/share/glib-2.0/schemas
```

If you're packaging ``rmlint`` you should indeed not install ``gschema.compiled``. If you're compiling ``rmlint`` from source, having the install process trigger this command is a good thing though - otherwise we would have to tell users to run this command by themselves. But for packaging, the ``gschema.compiled`` form should be skipped. I'm not sure what the best approach is here. Probably you can just remove ``gschemas-compiled`` from the destination dir, or I could also supply a switch or environment variable to skip to disable the call to ``glib-compile-schemas``. 

From what I [can see from the glib-compile-schemas](https://github.com/GNOME/glib/blob/master/gio/glib-compile-schemas.c#L2233) source it will place the compiled file in the source directory, so that should make problems either.

**Comment by lockywolf** [comment]
Well, I'm by no means a distro-building expert, but usually there is a "build" target and an "install" target. Usually it is fine to generate whatever is needed to run the program from the source tree, as long as it is not installed at the point of "make install", or its analogue.

**Comment by SeeSpotRun** [comment]
In developing a MacPorts port, I ran into permissions problems when trying to compile in the target dir (with good reason I guess, as per the OP).  The fix was https://github.com/SeeSpotRun/rmlint/commit/ac6efded314bfb31ad2cd42adffc8cef0de2dfac , which I think also addresses this issue.

Will merge this into `develop` and hope it doesn't break any other distros / packagers.

**Comment by SeeSpotRun** [comment]
Actually to make this work both ways:
> If you're compiling rmlint from source, having the install process trigger this command is a good thing

and 
> But for packaging, the gschema.compiled form should be skipped

I have, as sahib suggested, [supplied a switch ](https://github.com/SeeSpotRun/rmlint/commit/855beb70ccc32869186d2c911e92db30268b83e1)to skip the call to `glib-compile-schemas`.  Will merge into `develop` in due course.
