### ISSUE TITLE
rmlint (GUI) not scanning directories & rmlint (CLI) not allowing original tag search

### ISSUE THREAD

**Issue by russmcg** [sahib/rmlint#534]
I have noticed two issues with rmlint 

1. the rmlint GUI does not notice files in the directory I chose. It only notices the rmlint.sh files that were created from running rmlint in the /home/username/Pictures directory. 
2. only allows me to run rmlint command. running rmlint --keep-all-tagged --must-match-tagged /home/username/Pictures/PicturesinDrive-005 // /home/username/Pictures does not work 

currently running ubuntu 20.04.3 LTS 
gnome version 3.36.8

Not sure why it is only working when running just rmlint in the directory I am interested in, and the GUI isn't scanning either. 

Hope someone can help.

**Comment by russmcg** [comment]
I also installed all the dependencies even the optional ones to make sure it wasn't something to do with that

**Comment by tony-travis** [comment]
I've just reported this as a BUG in the version packaged for Ubuntu 20.04 LTS
https://bugs.launchpad.net/ubuntu/+source/rmlint/+bug/1951596

The problem is that the default 16 PB max file size is interpreted as a negative number.

This is the error running rmlint with the default 16 PB value:

ajt@pilot:~$ rmlint --no-with-color -T duplicates --see-symlinks --partial-hidden -c sh:handler=remove --hardlinked --crossdev --size 1-18446744073709551615 --max-depth 512 -o json -c json:oneline /home/ajt/Documents/Work/Minke
ERROR: cannot parse --size: Max is smaller than min.

**Comment by Cebtenzzre** [comment]
@russmcg I'm going to track the --size issue with the GUI here. Open a separate issue with more information about the CLI issue with --keep-all-tagged/--must-match-tagged if you are still able to reproduce it.
