### ISSUE TITLE
GUI don't launch

### ISSUE THREAD

**Issue by Adelineenileda** [sahib/rmlint#628]
When I try
`rmlint --gui`
Nothing happened and I have this error :
`File "/tmp/.shredder-bootstrap.py.UYW281", line 23
SyntaxError: source code cannot contain null bytes`

I am on Ubuntu 23.04

If you have a idea, thanks a lot !

Adeline

**Comment by Cebtenzzre** [comment]
What version of rmlint? Presumably 2.9.0 from the Ubuntu repos? Could you please try building the latest rmlint master ]from source](https://rmlint.readthedocs.io/en/latest/install.html)? (do not use `-b develop`)

**Comment by Cebtenzzre** [comment]
Actually, this looks like a bug in rmlint that affects python 3.12, which hasn't been released yet.

**Comment by RayOei** [comment]
For reference: 
* #253
* #419 

There are more facing similar problems over time. It seems just not _that_ stable of a solution.
We may have to have closer look how to proceed with this one: looks a bit as a can of worms 😁

**Comment by rsbrux** [comment]
Indeed. When I tried to install rmlint under Ubuntu Studio 24.04, KDE Discover only offered Shredder 2.9.0-2.3.
The installation included rmlint, which seems to work as intended from the command line, but Shredder doesn't launch, or crashes immediately.  No error messages are displayed.
When I try to run:
`rmlint --gui`
I get:
```
File "/tmp/.shredder-bootstrap.py.1ZZF32", line 32
SyntaxError: source code cannot contain null bytes
```

**Comment by RayOei** [comment]
The `source code cannot contain null bytes` error has been resolved in v2.10.2.

**Comment by arnoulfos** [comment]
could you post a compiled  deb package  of 2.10.2?

**Comment by RayOei** [comment]
Packages are not provided but you can build your own, see [building](https://rmlint.readthedocs.io/en/latest/install.html)

**Comment by arnoulfos** [comment]
I made all the process described but i get this error at the end 

scons: *** [gui/always.install] Error 1
scons: building terminated because of errors.

**Comment by arnoulfos** [comment]
I followed all the process described but i get this error at the end 

scons: *** [gui/always.install] Error 1
scons: building terminated because of errors.

**Comment by arnoulfos** [comment]
I followed all the process described but i get this error at the end 

scons: *** [gui/always.install] Error 1
scons: building terminated because of errors.

**Comment by arnoulfos** [comment]
And in the process i had 

Unable to locate package python-cairo

(I am with  ubuntu 24.04)

**Comment by vassilit** [comment]
> could you post a compiled deb package of 2.10.2 (because in ubuntu 24.04 is only available in the repositories the previous version tat doesn t work)?

20 hours ago, @bdrung pushed this [commit](https://git.launchpad.net/ubuntu/+source/rmlint/commit/?id=6dfbe5307f6c523113a6a8b4accaa7d0486374fe) of version 2.10.2 to Ubuntu packaged repository.

You can make a .deb package from this tag or wait for it to appear in the repositories.

2.10.3 would have been better however.

**Comment by vassilit** [comment]
See https://github.com/sahib/rmlint/blob/master/docs/install.rst

**Comment by arnoulfos** [comment]
thanks now i get this error

Linking Static Library ==> librmlint.a
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/_normalization.py", line 59, in safe_version
    return str(packaging.version.Version(v))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/_vendor/packaging/version.py", line 198, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
setuptools.extern.packaging.version.InvalidVersion: Invalid version: '2.10.1.Ludicrous.Lemur'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/portable/rmlint/gui/setup.py", line 90, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 147, in setup
    _setup_distribution = dist = klass(attrs)
                                 ^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 480, in __init__
    self.patch_missing_pkg_info(attrs)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 469, in patch_missing_pkg_info
    dist._version = _normalization.safe_version(str(attrs['version']))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/_normalization.py", line 62, in safe_version
    return str(packaging.version.Version(attempt))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/_vendor/packaging/version.py", line 198, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
setuptools.extern.packaging.version.InvalidVersion: Invalid version: '2.10.1.Ludicrous.Lemur'
Ranlib Library ==> librmlint.a
Linking Program ==> rmlint
scons: *** [gui/always.install] Error 1
scons: building terminated because of errors.

**Comment by vassilit** [comment]
Please use 2.10.2 package from Ubuntu.

**Comment by arnoulfos** [comment]
It is still not in the repositories do you know the delay for the repository to be up to date after the commit

**Comment by arnoulfos** [comment]
I fount it on launchpad.net, it is now working thanks a lot!!!

**Comment by vassilit** [comment]
> It is still not in the repositories do you know the delay for the repository to be up to date after the commit ?

https://packages.ubuntu.com/oracular/rmlint
